// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgoLS7As-yZueSmJC-ypmsWp0vIEPy06s',
    appId: '1:515904665523:web:c47d1eb73c6bbd9989bdc6',
    messagingSenderId: '515904665523',
    projectId: 'bitirmeprojesi-9de84',
    authDomain: 'bitirmeprojesi-9de84.firebaseapp.com',
    storageBucket: 'bitirmeprojesi-9de84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBItz-v-Mmb3HGDLPxPyJ2oe-4BXxErKsU',
    appId: '1:515904665523:android:84b034c0175ebb3989bdc6',
    messagingSenderId: '515904665523',
    projectId: 'bitirmeprojesi-9de84',
    storageBucket: 'bitirmeprojesi-9de84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ-a4B4ciyLwFXHxxWSwynN1_pR-uq9Rk',
    appId: '1:515904665523:ios:eceff2f4347411ea89bdc6',
    messagingSenderId: '515904665523',
    projectId: 'bitirmeprojesi-9de84',
    storageBucket: 'bitirmeprojesi-9de84.appspot.com',
    iosBundleId: 'com.bitirmeprojesi.bitirme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ-a4B4ciyLwFXHxxWSwynN1_pR-uq9Rk',
    appId: '1:515904665523:ios:cb41d11b1695bdfa89bdc6',
    messagingSenderId: '515904665523',
    projectId: 'bitirmeprojesi-9de84',
    storageBucket: 'bitirmeprojesi-9de84.appspot.com',
    iosBundleId: 'com.bitirmeprojesi.bitirme.RunnerTests',
  );
}
